### ISSUE TITLE
Empty steamid with offer

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#124]
## Describe the bug
As you can see [here](https://barter.vg/u/48e/o/3372026/json), `to_steam_id` is an empty string. This bug is specific to this offer, because in another offer with this trader, his steamid is returned correctly.
You also notice this on the barter site itself. The steam message link is `steam://friends/message/` (without steamid), yet the link to his steam profile and steamdb calculator is correct.

## Steps to reproduce the bug
No idea how this is caused.

## Expected behavior
Return the steamid.

## Screenshots (if helpful)
![image](https://user-images.githubusercontent.com/4411977/80044945-4dd00d80-8506-11ea-846a-6a1adf6d18bc.png)

**Comment by bartervg** [comment]
This is due to a bug with multiple-user offers. The join and accept function doesn't set the SteamID64 and therefore it remains empty.

**Comment by Revadike** [comment]
> This is due to a bug with multiple-user offers. The join and accept function doesn't set the SteamID64 and therefore it remains empty.

Can you fix it though?

**Comment by bartervg** [comment]
> Can you fix it though?
If it was due solely to the multiple-user offer accept bug, then it should be fixed now. 

I retroactively updated the SteamIDs of 2572 offers, going back to offer #9038. There were a total of 10276 offers with blank Steam IDs, but since most of these were not to any user and never accepted, the remaining 7704 offers wouldn't have SteamIDs.
