### ISSUE TITLE
Edit wishlist parameters from item page

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#139]
# What problem does this feature address?
It's (sometimes) tedious to go into your wishlist collection to edit tags (tier tags and extra tag). It would (sometimes) be a lot easier to edit it right from the item page, like you can do with tradables.

## Describe a solution
A solution would be to add a full-fledged row to edit the wishlist entry like you would with the tradable entries. I realize that you can use the trading tag editor on the item page to add parameters to your wishlist entry _when adding the item to your wishlist_, but AFAIK you cannot edit the wishlist entry in the same way after it has been added. 

One workaround (well, aside from going into your wishlist) is to just click the remove button, and then re-add it with new trading tags in this aforementioned method, but then you will lose your "spot" in the wishlist list on the item page, as it's sorted by date added to wishlist (and tiers). 

The wishlist entry could be listed just like a tradable entry and be edited like one. A disadvantage is possibly more confusion and more clutter. 

## Examples of similar features
Editing tradables right from the item page

**Comment by bartervg** [comment]
Copy and pasted the tradables code on the item profile page. This conflicted with tradables because all of the code assumed it was changing a single collection. I think it is working now, but there may be unseen side effects.

![image](https://user-images.githubusercontent.com/28576132/82406043-a1fddd00-9a33-11ea-8967-964efc0550f8.png)

Add Another Wishlist button didn't seem necessary. Except for 0, quantity is mostly useless, although it originally used the wishlist rank in this column. The stores seem irrelevant to wishlist, but there's an addition in the code that allows this to appear on the wishlist edit bar. I don't remember the reason why so I left them. The select all doesn't work correctly when there are tradables and wishlist.
