### ISSUE TITLE
Items remain in Barter library after being removed from Steam library

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#140]
## Describe the bug
If a game is revoked or a free weekend Steam game is synced and added to your Barter library, it does not go away when the free weekend is over or the game is revoked. 

This makes your library inaccurate and makes it hard to get the games you had back through trading. If the game is added through sync, it is not even possible to manually remove it from library.

I could not see a github issue for this, but I believe that this should have some sort of priority, but that's just my opinion.

## Steps to reproduce the bug
1. Own some games, have them synced to your Barter library
2. Remove or have a game removed from your Steam library
3. Observe that it still stays in your Barter library.

## Expected behavior
The game is removed from your Barter library and you can receive offers containing the game again.

### Additional context
Here's an example, XCOM 2 is in my barter library due me having it on my account for a free weekend at some point: https://barter.vg/i/14169/

**Comment by bartervg** [comment]
![image](https://user-images.githubusercontent.com/28576132/82781926-22a04d00-9e29-11ea-86ff-60b564dee144.png) 🤦 

There haven't been any items added to revoke since December of last year. The problem seems to be that I made library API the primary method of syncing whereas previously it had been using the library web page (due to inertia and because it included the Steam limited games). Once large libraries reliably prevented the page from loading at all, the API was the only method to automatically sync library. That change was simple, but the method was not setup to process revokes (as shown in the screenshot).

However, I couldn't get XCOM 2 to appear as revoked for @Tecfan library. Then I checked the Steam library through the API and the website and it shows XCOM 2 there.

**Comment by bartervg** [comment]
Other than the XCOM 2 example, I believe revoked is working again.

In addition, playtimes update (as library quantity), and if the game appears in the API sync it will change any custom addition to `sync-api`. This will increase revoked tracking.

>  it is not even possible to manually remove it from library.

All items are editable now. The reason for this was to avoid confusion of removing library and then having it reappear after a sync. However, not sure if this does avoid confusion, but it does limit potentially useful editing.

**Comment by Tecfan** [comment]
I activated XCOM 2 the same day that I posted about it on Discord, so I do own it now. Whether or not it actually was in my library at the time I screenshotted this is now impossible to know. Might have just been brain lag.

**Comment by bartervg** [comment]
Thank you for posting this bug.

Revoked detection was not working then and hadn't worked all of this year. In addition, I fixed the since-the-beginning lack of playtime updating and implemented Madjoki's suggestion to switch custom to sync.

**Comment by Tecfan** [comment]
I got some false positives in my revoked collection now, like DayZ and Toki Tori 2+ Level Editor. But they are still in my Steam library and my Barter library, so not sure what happened there.

Seems like the banned games I added with the userscript is not removed because they are custom additions right? I removed Athopiu - The Final Rebirth of Hopeless Incarnate + DLC's manually now.

**Comment by bartervg** [comment]
DayZ and Toki Tori 2+ are my fault. I was resyncing your library while testing in a fruitless effort to get XCOM 2 to disappear 😄. The early attempts mixed up the API and Community syncing.
