### ISSUE TITLE
More wishlist trading tags

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#147]
# What problem does this feature address?
There's a two problems with the current wishlist trading tags:

0: If you select a specific "Store", let's say "Steam, inventory gift" or "IndieGala", the "+ extra copy" tag disappears. You can't have both a store tag a "+ extra copy" tag, I think this should be possible, because "extra" signifies certain things for traders.

1:  We need more or different trading tags. Currently we have "Humble gift link", however, as a future possible re-trader, "Indiegala gift link" and "Groupees gift link" will be just as valuable – the main point is that the other party has not yet seen the key. 

## Describe a solution
I suggest that we either add more trading tags, or that we replace "Humble gift link" with a more general "Gift link". Everybody who currently has a "Humble gift link" trading tag should get it replaced by a "Gift link" trading tag + a "Humble Bundle" Store tag.

However, this requires that problem 0 is solved, as the Humble Bundle Store tag would replace the "extra copy" tag. 

## Examples of similar features

**Comment by bartervg** [comment]
More tags seems like the easiest option with the least chance of breaking something else, therefore added Indiegala and Groupees gift link tags. If there are other options, will add more tags.
![image](https://user-images.githubusercontent.com/28576132/82777889-93416c80-9e1d-11ea-9bd0-9df853845b08.png)

I haven't done much Groupees trading. How does the gifting / trading option work? Are there links?

0: this is due to inflexible design. The original goal was to avoid mismatched combinations such as Steam store Steam keys (which seems logical to new users) or Fanatical inventory gifts. Therefore setting the store also sets the type. Given the new tags, I'm not sure if it is worth fixing to allow Extra + store.

**Comment by Tecfan** [comment]
Groupees is the same as any other, you can generate a gift link, trade with other users within their platform, or generate a key. Thank you!

**Comment by Tecfan** [comment]
Is it possible to tackle "issue 0" somehow? I'm afraid my "humble gift link" trading tags will exclude people who have a Steam inventory gift copy. 

![image](https://user-images.githubusercontent.com/956878/83861693-300ae080-a721-11ea-90e6-bfbd33e7f5eb.png)

This kind of looks like I will accept everything else but a Steam inventory gift.
