### ISSUE TITLE
Dynamic or linked monetary trading tags

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#163]
# What problem does this feature address?
If you want to trade a game for let's say gems, TF2 keys or other semi-monetary items, you will have to first of all manually compute and convert between currencies, then add them all manually and also update them manually.

Example: 
A tradable with trading tag "1 TF2 key", "6000 gems", "40 trading cards".

This is a lot of work, especially if you want to put a price on hundreds or thousands of tradables.

## Describe a solution
Can we have dynamic or linked trading tags? Barter would take no responsibility for the conversion, but let's say you set a price (e.g. in EUR/USD or in gems/TF2 keys), and then other tags of your choosing automatically fluctuate and populate the tradable.

For example: You add that you want $5 for a tradable (for example the latest $8.5 HB tier 4 with 2 games, DayZ). Then the trading tags "X gems" and "Y TF2 keys" etc. are automatically calculated, added and updated with daily rates. Would make life easier.

In this case, the TF2 key would not be rounded up though.

## Examples of similar features
Calculator

**Comment by Tecfan** [comment]
Another option is to just add a "currency" trading tag, which may include a :hover function to automatically show conversions to other currencies or price in gems/keys.

Or just a "currency" trading tag (maybe USD/EUR to start with), and some smart guy might make a user script to convert this tag to other tradable items.

**Comment by Tecfan** [comment]
Here is an example of a profile that could benefit from dynamic trading tags: https://barter.vg/u/1a01/t/

**Comment by Luckz** [comment]
At present you can put USD-cent (or tenths of cents) values into 'userfield' to achieve listing things for a real world currency price.

----

Autoconversion to other Steam items is problematic due to the horrendous disagreements about their valuation. Example: "s-usd" on Archi's Discord bot, which you can use to show the ratio at which Archi relates real fiat USD to Steam wallet USD:
```
[16:06] luckz: !convert 10 usd s-usd
[16:06] ArchiBot: 10 usd = 12.5 s-usd
```

----

Conversion between gems and TF2 keys is fine as they are both on-Steam currencies and thus it can be done using market rates updated maybe up to once a day, but this should be polled in a market currency more finely grained than USD, and I'm not sure Barter's infrastructure currently allows for this. (& I don't know the market APIs at all.)

**Comment by Tecfan** [comment]
bartervg/barter.vg#35 is also relevant here.

**Comment by Tecfan** [comment]
Is this suggestion out of scope even without the "monetary" part? Dynamic tf2/csgo/gem ratios. Enter just "5000 gems", get "1 TF2", "0.5 CSGO", "2 ToD" automatically?

**Comment by bartervg** [comment]
> 
> 
> Is this suggestion out of scope even without the "monetary" part? Dynamic tf2/csgo/gem ratios. Enter just "5000 gems", get "1 TF2", "0.5 CSGO", "2 ToD" automatically?

Yes, although ArchiBot does this type of conversion, the Barter site doesn't and doing do be out of scope. Although I was snarky, I honestly believe that this would be better served with a dedicated project. There isn't much now, but once the basics are established, I think it will be a lot better than bolting on new things to an old site https://github.com/bartervg/notamarketplace

**Comment by Revadike** [comment]
This feature was actually part of my [marketplace suggestion](https://github.com/bartervg/barter.vg/issues/35)
