### ISSUE TITLE
Editing toolbar for notification collection items does not load on item pages when it is the only collection an item is added in

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#170]
## Describe the bug
Sorry for the long title. A screenshot will be more useful:

![image](https://user-images.githubusercontent.com/956878/90855375-c5605d00-e37f-11ea-9c60-5d45698fa0ad.png)

The "Move" part and the "Set" button of the editing toolbar for the Notification collection item is missing. This is consistent across browsers and item types. If another "wishlist editing group" collection type is added (like wishlist or watchlist), then the editing bar appears in full:

![image](https://user-images.githubusercontent.com/956878/90855480-02c4ea80-e380-11ea-82a4-5c4ca7618fb5.png)

## Steps to reproduce the bug
1. Go to any item page that you have not added in wishlist or watchlist
2. Click the notification bell
3. Observe that there is no way to tag this collection item.

## Expected behavior
I should be able to tag my notification collection items on the /i/ page.

### Device (if applicable)
 - Browser: Chrome, Firefox

**Comment by bartervg** [comment]
Many of these problems are due to adding a new collection type into a place where only tradable or wishlist was expected previously or expecting that wishlist will always be present with notification.

![image](https://user-images.githubusercontent.com/28576132/106207501-dc597580-618f-11eb-9185-c8958e2f3ead.png)
