### ISSUE TITLE
Add an "exclude tradeables collection" filter to the browse page

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#174]
# What problem does this feature address?
A need to not see games in a search that you already have up for trade (but not in library).

## Describe a solution
Add a "exclude tradeables collection" filter to the browse page.

## Examples of similar features
"exclude owned or blacklisted"
"exclude owned, blacklisted or wishlisted"

![image](https://user-images.githubusercontent.com/956878/92326603-a9350f00-f053-11ea-8f8a-5be0078a1336.png)

**Comment by bartervg** [comment]
Added exclude tradables. 
![image](https://user-images.githubusercontent.com/28576132/103459857-da5edc80-4cdf-11eb-9b49-3f2309cd8ddc.png)

Either I do not understand how this was implemented previously, or it was not working correctly. In addition `owned` was ambiguous and referred to library, or library and tradables. I removed `owned` and use the collection names instead. 

Rather than enumerate every permutation of what to include or exclude, a future browse could have include / exclude for each collection.

**Comment by Tecfan** [comment]
Since I made this thread, I have temporarily moved all my tradeables to reserve collection, so I cannot used this option after all. Could it be "exclude tradeables and reserve"?

**Comment by bartervg** [comment]
![image](https://user-images.githubusercontent.com/28576132/103460195-578b5100-4ce2-11eb-9cfd-fc4b167af0a1.png)

**Comment by bartervg** [comment]
This seems to work, but the naming of variables was short sighted. It is setup to exclude library, tradables, blacklist or wishlist by passing the collection IDs as function parameters. I could change that to include reserve or use generic names, but I just changed the blacklist collection ID to the ID of the reserve collection.
