### ISSUE TITLE
Setting bundle tag to "[no bundle]" at the same time as adding a store, results in the store tag missing, but the "key/link/gift" tag not missing

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#181]
## Describe the bug
Setting bundle tag to "[no bundle]" at the same time as adding a store, results in the store tag missing, but the "key/link/gift" tag not missing. A screenshot will help explain:

Before:
![image](https://user-images.githubusercontent.com/956878/92328624-5f9ff080-f062-11ea-9577-e04d6665232e.png)

After:
![image](https://user-images.githubusercontent.com/956878/92328625-63337780-f062-11ea-841d-ef486c71adee.png)

I set "Steam" as the Store, but the Steam icon is missing. However, the "gift" part of the tag is still there. This also applies to other things like "Groupees, gift link". 

## Steps to reproduce the bug
0. *have a tradable "Livelock" from Indiegala store, gift link.*
1. Go to https://barter.vg/i/22286/
2. Add a new tradable with a bundle tag, for example "Very Positive Bundle 4"
3. Realize you set the wrong tag, so add "Indiegala, gift link" as store and set bundle to "[no bundle]"
4. Observe that Indiegala icon is missing.

### Additional context
> this issue is only something i experience because of the issue of adding new tradables (different subid/source) on items where there's already a tradable with "other store, key" set. if you click "Add Another Tradable" in these instances, this "other" tradable is just selected and no new tradable is added. Normally the workaround is to temporarily tag this non-store-tagged tradable with a fake store, then add a new tradable, and then remove the fake store. recently I started just selecting a fake bundle for my new tradable and then removing it after, which saves me a couple of clicks. but then I get the bug as described above. sorry for this mess of a paragraph

**Comment by bartervg** [comment]
The `No Bundle Tag` removes both the bundle and the store. This is the intended effect since setting a bundle sets both the store and bundle. Thus removing it resets both the store and the bundle. Since it doesn't modify key/link/gift, it doesn't change that.

`No Bundle Tag` is now `No Store or Bundle tag` and there is a new `No Bundle Tag` that doesn't change the store or the key/link/gift. In order for `No Store or Bundle tag` to be consistent with `No Store Tag`, key/link/gift is reset to the blank default.

![image](https://user-images.githubusercontent.com/28576132/106206019-69e79600-618d-11eb-9aee-2550d9099669.png)
![image](https://user-images.githubusercontent.com/28576132/106206047-74a22b00-618d-11eb-8d5a-7b3629559e3c.png)

For even more improvement, should the `No Store or Bundle tag` be executed before setting `Steam, inventory gift`? Probably, but I hope that using offsetting tags isn't a common scenario.

I don't understand the purpose of using fake store tags. Why not use the actual stores when adding tradables?

**Comment by Tecfan** [comment]
> I don't understand the purpose of using fake store tags. Why not use the actual stores when adding tradables?

Due to #182
