### ISSUE TITLE
Add vLoot as Store

### ISSUE THREAD

**Issue by Tecfan** [bartervg/barter.vg#209]
# What problem does this feature address?
Add vLoot as Store as they have frequent giveaways via Gleam.

## Describe a solution
Add vLoot as Store as they have frequent giveaways via Gleam.

## Examples of similar features
MMOBomb, Intel are examples of "Stores" that exclusively use Gleam but are nonetheless added to the system

**Comment by lillje** [comment]
As you clearly observed, these are Gleam keys, not vLoot keys.
vLoot should / will not be added as a store.
MMOBomb and Intel should also not have been added in the first place.

**Comment by Tecfan** [comment]
Completeness and accuracy has always been an aim for barter.vg. See for example here: https://discord.com/channels/329829406153375755/329829406153375755/700783281989222511

Devil's advocate: vLoot use Gleam as a service, but hosted on their site (via embed). Several stores use the same payment/delivery method as other stores, but that does not mean that we do not add them. If a site delivers keys via email, we do not add "Email" as a store. Gleam is a pretty inaccurate source, as the same game can be given away multiple times by multiple sites, all using Gleam, and we would have a pretty hard time differentiating the keysets for possible giveaway revocation alerts, etc.

In addition, it also gives new users a new place to bookmark/follow/browse, when they see the icon/store on barter. Gleam is not a "site" where you can discover new giveaways. My two cents.

**Comment by lillje** [comment]
It's been almost 1 year since you requested the addition of  MMOBomb and considering that there are barely any items listed under this store, this should prove that your argument that "it also gives new users a new place to bookmark/follow/browse" is not valid. Same goes for Intel - it has even less items than MMOBomb.

We aim for completeness and accuracy but a clean database is also one of our more important goals. New stores should be added only when there is a solid reason to do so: it sells keys / it's a serious giveaway site / it benefits multiple traders (not only yourself) etc. In its current state, vLoot is only a clickbait and far from being an established giveaway site.
As you can see, ITAD also has a very restrictive list of store and doesn't add any kind of junky site, so why should we?

**Comment by Tecfan** [comment]
As I argued for, I see value in having these sites added as Stores. But if the admins disagree, I would rather that the other Gleam-sites are deleted and all items in all collections be changed to or moved to Gleam.

Another way to tackle tradable sourcing issue would be the ability to tag tradables with giveaway, like you would with bundles. I vaguely remember discussing this on Discord, but I could not find any github issue for this idea.

Here is a real world example: 
![image](https://user-images.githubusercontent.com/956878/104836312-5c88fc80-58ad-11eb-9be8-ae61be69031b.png)

Intel [Gleam] keys are working.
Gleam [Alphabetagamer.com] keys have a high duplicate rate.

If these were merged users would have a harder time tracking which tradables are at risk of being duplicate. Alternative ways to tackle this is: add "revoked?" tag with "2" integer tag value (so 2 out of 3 tradables might be duplicate), or add a separate Gleam tradable with "revoked?" tag and one tradable without this tag (would require you to add a fake/non-store tradable first, and then change it to Gleam after, as Barter does not support adding two tradables from the same store without unique bundle tags).
