### ISSUE TITLE
Expire "require action"-offers

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#21]
So, not only offers that are in "creating" stage, but also expire offers that require action for any side.  Of course, the expiry time should be much longer than the "creating" expire time for these. 
This allows offers of accepted-expire, completed-expire, failed/cancelled-expire and vice versa to exists. Imo, these should still count towards your stats, but this is debatable.
A cron job that queries offers and check them could be how this can be implemented. Thanks to @carlmundo for the original suggestion.

**Comment by Revadike** [comment]
I'm not sure if this still an issue anymore? Currently, I'm not seeing any ancient/old "require action"-offers on my offers page. 
Are you hiding them? If so, how can we find them, if we want to? @bartervg

**Comment by bartervg** [comment]
These were rare and I did add cron jobs to search for and fix them, but from what I've heard since, database triggers would be a better solution. However, it seems to be working well enough, and thus solved for now.

> these should still count towards your stats

I believe this would be addressed with #256 and allowing a user to switch side to act, and thus changing the party responsible for the expiration.

**Comment by Revadike** [comment]
#256 would indeed solve this, now you mention it.
