### ISSUE TITLE
+1 marker for games that increment game count on profile 

### ISSUE THREAD

**Issue by d4rckh** [bartervg/barter.vg#232]
# What problem does this feature address?
This would tell people if a game increments the game counter by 1 on the steam profile (also known as +1)

## Describe a solution
A small button on game page which upon pressing it, the user reports the game as giving +1.

This would be soooo useful as a lot of people's question is "does this game give +1?".

**Comment by antigravities** [comment]
Games that count as +1 are not banned (⎚ in offers/on item pages) and not profile limited (⚙️  in offers/on item pages). You can also trivially determine whether a game counts towards your profile's number if the Store page does *not* contain the "features" "Profile Features Limited" and "Steam is learning about this game." There is also a [tag](https://barter.vg/browse/tag/531/) marking games that add to game count, but tags on item pages sometimes appear to be incorrect or outdated.

**Comment by bartervg** [comment]
#231

**Comment by bartervg** [comment]
As antigravities mentioned, the `Steam plus one` tag exists and can be browsed at https://barter.vg/browse/tag/531/ 
![image](https://user-images.githubusercontent.com/28576132/107045845-fe588680-6793-11eb-818f-a47067acd6a2.png)
Would you recommend making it more visible somewhere else on the page?
  
As at least one person has reminded me, the major limitation of the +1 tagging system is that Steam determined +1 by the subID, and the game profiles on Barter.vg are appIDs (for the most part). For example, a game could go from paid to free on demand. Anyone that purchased the game should get +1, anyone that adds the free on demand version won't.

**Comment by d4rckh** [comment]
when choosing games to trade with someone, there could be a little +1 marker.

**Comment by Revadike** [comment]
I can imagine this enables the trade preference of only accepting +1 games, which would be pretty nice.

**Comment by Luckz** [comment]
> I can imagine this enables the trade preference of only accepting +1 games, which would be pretty nice.

The tag is there already, but we need to determine if it's applied correctly. Like, how do we find edge cases of what gives +1 and verify the tag is applied correctly, and functions correctly for all variations of decom products?
We might also want "plus-more-than-one" support, for tradables that give you several entries.

At least DLCs also have the distinction between +1 (tracked via profile count) and +0 (does not increment profile DLC count), eh?



> As at least one person has reminded me, the major limitation of the +1 tagging system is that Steam determined +1 by the subID, and the game profiles on Barter.vg are appIDs (for the most part). 

Outside of curator trades, which are not exactly the target group in the first place, a traded copy should always "+1 as much as possible", since you can't trade a Free on Demand item. So for purposes of trade preferences, it's enough if any +1 version could exist, and you filter out curator tradables. We don't have access to an automated system to determine which games' curator versions would be +1-qualified.
I mean, **I guess** if the developer changes a Store package to a FoD package, you might have _a FoD key_? And perhaps that's not a +1 then, while it was before (as Store / Retail) or is with other packages.

**Comment by Luckz** [comment]
Also, don't forget to consider _non-game_ things that yet give "game" +1.
I guess make available to trade to someone who wants +1s?

**Comment by bartervg** [comment]
This is the logic from plus_one_tagging.php translated into English 

Steam platform AND
game, application, mod AND 
NOT S-T Test App, F2P (unavailable), Delisted video, Free software, Unreleased software, Banned AND
NOT Steam profile limited AND
NOT is_free OR is `No Cost` AND 
NOT adult OR is tagged `Steam plus one` AND
NOT tagged free on demand AND
NOT tagged `Steam plus zero` AND 
NOT is_free OR is Steam-Tracker Delisted, Purchase disabled, Retail only OR `No Cost`

**Comment by bartervg** [comment]
https://github.com/bartervg/barter.vg/blob/develop/data/playtests.txt 

I added `Steam plus zero` to all of them. Some of them didn't count as +1 already, e.g. https://barter.vg/i/118820/ due to Steam-tracker `Test app`

**Comment by d4rckh** [comment]
I remember there being a giveaway with some keys that would activate a package with 2 games (both +1 but one of them did not have a store page)

**Comment by bartervg** [comment]
![image](https://user-images.githubusercontent.com/28576132/107297581-a9da3300-6a41-11eb-8bdd-b444c9fbd297.png) This +1 tag appears on the offer page, in the place where the `⚙️` Steam Limited tag would appear. 
![image](https://user-images.githubusercontent.com/28576132/107297549-9929bd00-6a41-11eb-8778-4ba18e49106a.png)


It shown when selecting games for an offer also
![image](https://user-images.githubusercontent.com/28576132/107299956-8bc30180-6a46-11eb-8fd8-3787405490c7.png)


Again, it's an estimation based on an ad hoc model.  Looking at luckz's library https://barter.vg/u/427/l/ Steam Games Owned: 15607; Barter Estimation: 15454, shown as the estimation error of `(153 ε)` (probably makes more sense if it were negative). Since this is the net difference, it's possible there are more than 153 inaccuracies. 

The +1 system is a long-term upgrade, but I believe this issue is completed.

**Comment by Revadike** [comment]
do curator games give +1?

**Comment by Revadike** [comment]
> do curator games give +1?

@bartervg @Luckz

**Comment by bartervg** [comment]
> 
> 
> > do curator games give +1?

Isn't this a SteamDB question? Although, I think at this point after any pre-`DisableGameCount` packages have expired, the answer is no.

**Comment by Revadike** [comment]
Most, if not all, curator connect packages from 16 months ago and newer have this:
![image](https://user-images.githubusercontent.com/4411977/113509308-275b8480-9555-11eb-892b-eee5ab95b1f3.png)

Therefore, I suggest hiding the +1 tag for tradables tagged as curator connect games.

**Comment by bartervg** [comment]
> Therefore, I suggest hiding the +1 tag for tradables tagged as curator connect games.

Before change
![image](https://user-images.githubusercontent.com/28576132/113509495-e72fde00-9523-11eb-808b-be454e24431d.png)
After change
![image](https://user-images.githubusercontent.com/28576132/113509499-ef881900-9523-11eb-90a1-b077b86c9fba.png)
![image](https://user-images.githubusercontent.com/28576132/113509764-52c67b00-9525-11eb-9cc6-e614c7da1cc5.png)

**Comment by Revadike** [comment]
@bartervg why does this not count as +1: https://barter.vg/i/8726/ ?
Because it does. I tested it.

**Comment by Luckz** [comment]
> @bartervg why does this not count as +1: https://barter.vg/i/8726/ ?
> Because it does. I tested it.

Free licenses are listed as plus zero: `NOT tagged free on demand AND`
You can of course own a free game, and if it's not PFL or such it will be +1 then. We don't have a good way of marking this in your library collection either (believe me, I tried a few).
Of course maybe since we're still foremost a trading site, there's the case that we shouldn't list FoD games as +0 unless they're also PFL because **tradables** will be +1. But if we change that, I'm sure there will be some users complaining that they claimed the free license and did not get a +1, and to make matters worse there are various exotic free licenses that DO give a +1 for more or less understandable reasons. https://www.steamgifts.com/discussion/fZdnc/free-steam-games-that-add-1-to-steam-games

----

PFL = Profile Features Limited (or Steam is Learning ...)
FoD = Free on Demand

**Comment by Revadike** [comment]
PFL?

**Comment by Revadike** [comment]
License 'Offworld Trading Company - Free Multiplayer' is not free though. It has billing type CD key. Also, it's included app is not free. 


https://discord.com/channels/329829406153375755/438406560222281738/1316576177975984128

notv37 — 12/12/2024 03:43
Kind of. It's first and foremost based on appid (type + limited/learning), second on billing type of sub, and finally on flag set on sub that exclude count on sub type that would otherwise count. Ban means restriction readded.

If app type is Game or Application and appid doesn't have profile features restricted/learning, then subs with license type Store (1), CD Key (3), Store or CD Key (10) will always count. No Cost (0) counts unless DisableGameCount is set to true, which is normally set on Curator Connect subs but not set on free to keep promotions (those just get DisableTradingCards). Free on Demand (12) never counts.

F2P games can be +1 if non-restricted and activating a key for a non-FoD sub (notably beta keys that are often given away in promos). There are also F2P games that have their appid included in a non-free sub such as a DLC/premium package. There are also those that are only in a NoCost sub, such as Valve's very own Artifact -- but this is rare.

Throne and Liberty was +1 for early access sub which included base app, but now the DLC is sold standalone and base appid is only FoD. https://steamdb.info/app/2429640/subs/
Path of Exile 2 is currently +1 in early access -- this may change if it follows Throne and Liberty and becomes available as only FoD once early access ends.
World of Tanks has a NoCost sub included in a paid bundle which gives +1 https://steamdb.info/bundle/36237/

Which sounds like a bit of a complicated mess, because it is, but for the purposes of trading it's a very simple rule of thumb is:
If app is non-restricted (banned = restricted), is game/application, and is key, it's +1.
If it's curator connect then not +1

The wild and rare exceptions are:
Keys can technically exist for FoD and Curator subs that are excluded. Valve doesn't normally allow it, but some exist.
Some very, very old curator connect subs didn't have DisableGameCount set
Games can have app type change (HL2 eps game->tool, JDM: Rise of the Scorpion game->demo)
