### ISSUE TITLE
Streamline dupe replacement process

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#268]
# What problem does this feature address?
More often than I care to admit, I have to replace a game, because its steam key is duplicate. And because stock is limited, the replacement often ends up being different from the agreed upon game. There is currently no good way for barter.vg to deal with this, other than to either complete the existing trade offer, or cancel the current trade offer and make a new one. In both cases it is not clear what happened.

## Describe a solution
I have two solutions: an easy and a harder one. 
The easy solution is to add another cancel reason (one that doesn't lead to a dispute, because we've already worked a potential dispute out), which handles this case. For example, "what I received was invalid, but a replacement will be provided". Ideally, after this reason has been chosen a new trade will be opened with the same item(s), except for the replacement side. 
The second harder solution is to allow changing the trade after acceptance (if both parties agree).

**Comment by bartervg** [comment]
There is `agreed to modify`, but it hasn't been implemented 
https://github.com/bartervg/barter.vg/issues/162

**Comment by bartervg** [comment]
At the risk of creating another half-finished feature, now testing `agreed to modify` https://barter.vg/u/a0/o/4080383/ 

If both sides `agreed to modify` then the offer should (when it works) go back to the creating status.

**Comment by bartervg** [comment]
Some problems:
Creating offers can expire. Therefore, the expiration date has to be updated, otherwise, the offer could immediately expire after both sides fail the offer.
This would provide a way to cancel accepted offers. For those that care about fulfillment rates, there would be an incentive to agree to modify every offer and then cancel it, which is different than agreed to cancel.

**Comment by Revadike** [comment]
RIP
just now X Revadike failed (agreed to modify) offer with Barter.vg  activity ☷
Next Step: resolve dispute  note 📓

**Comment by bartervg** [comment]
![image](https://user-images.githubusercontent.com/28576132/208748011-382416db-1788-4a93-bad2-f59e381dc7da.png)
Now when both sides agree to modify, the offer changes to `creating` status and the original sender can modify the offer. However, the cancel and discard option is not available. This is to prevent using `agreed to modify` as a way to cancel without it appearing in offer statistics.

**Comment by bartervg** [comment]
from the linked issue
> Not sure what I meant here. Trades aren't support to stay open for a long time anyway.

If the game is revoked, then there is an option to dispute the offer, even long after it was completed. If the key does not work because the user did not activate it before completing the offer, then this is not an ideal use of the offer system. This is like leaving positive feedback on ebay before the product arrives, then sometime later discovering that the box that arrived is empty and trying to undo the feedback. This is a will-not-fix / lots of manual support problem.

However, if the user discovers the problem before completing the offer, `agreed to modify` #162 seems like the solution to this issue.

**Comment by Revadike** [comment]
Cool, nice change
And surely you didn't simply hide the buttons, right? 😏

**Comment by bartervg** [comment]
> And surely you didn't simply hide the buttons, right? 😏

You've inspired me to think behind hiding UI elements. 

The restriction is written into the SQL query. However, maybe there's a way around that, so small bug bounty if you're able to cancel an agree-to-modify offer. Automatic cancellation (which is a bug, but a different one) or expiration not included.

**Comment by arseny92** [comment]
> If the game is revoked, then there is an option to dispute the offer, even long after it was completed.

How that should work, the disputed side can select replacements and they are recorded in the offer as replacement, or is it limited to resolution in offer comments or private in chat, then mediating and status reset with the new games?

This issue can probably be renamed to "Streamline dupe and revocation replacement process". Similar features: replacement games status in bundles.

**Comment by arseny92** [comment]
Revocation disputes shouldn't be counted (tooltip does not and should not include those), and especially when there are no tools yet to facilitate the process within the same offer that was disputed for revocation. This is resolved

<img width="739" alt="image" src="https://user-images.githubusercontent.com/13212955/209568154-cfabcc35-de6c-466d-8a3b-14dccf7c1029.png">

**Comment by bartervg** [comment]
> Revocation disputes shouldn't be counted

Revocation disputes are counted due to the possibility that the keys were fraudulently acquired.  This has happened at least once and affected multiple users. Without this option, there isn't an self-service recourse. 

In cases of keys getting revoked 10 months after trades, then it's more likely due to the developers or publisher making mistakes. What would you suggest? A `probably-not-a-dispute revoke` button.
