### ISSUE TITLE
Blocking users indefinitely no longer works.

### ISSUE THREAD

**Issue by Tylarion** [bartervg/barter.vg#311]
# Describe the bug
When you Ignore & Block a user while setting the time limit to indefinitely it will say "You will not see new matches, offers, or messages from this user for 53 years ago or until you remove the ignore." and the user will be no longer blocked after a day has passed.

"53 years ago" makes me think that it is setting the Unix Epoch as time limit.

## Steps to reproduce the bug
1. Go to a user.
2. Under contact preferences set "[until]" to "indefinitely"
3. Click Ignore & Block.
4. Wait a day.
5. User is no longer blocked.

## Expected behavior
That the text will say "You will not see new matches, offers, or messages from this user indefinitely or until you remove the ignore."
And that the user remains blocked.

### Screenshots
![Barter block bug 2023-05-24 221815](https://github.com/bartervg/barter.vg/assets/36107102/dd876202-a811-462d-915e-9c2a773de939)

### Additional context, device information (OS & Browser) if applicable 
Old ignores that were set to indefinitely are unaffected.

Using Firefox on Windows 10 Pro.
Someone mentioned having this bug on Discord, so it is not just me.

**Comment by bartervg** [comment]
This is due to a negative increment hack. The ignore time is set based on the pulldown value + the current time. To achieve `indefinitely`, the increment is a sufficiently large negative number such that the resulting unix time is negative. Negative times are treated as `indefinitely`. However, that negative number stopped being sufficiently large sometime in 2023.

Ideally, there would be a better system, but the quick fix is going to be to push this bug 1000 days into the future.

**Comment by bartervg** [comment]
The negative increment was 19500. 19500 days from 1 Jan 1970 was 23 May 2023. Therefore, any indefinitely long ignores set on or after that date will have been erroneously removed. However, all indefinite ignores set before 23 May 2023 should still be active.
