### ISSUE TITLE
Blacklist comprehensive sync broken

### ISSUE THREAD

**Issue by milroneth** [bartervg/barter.vg#316]
# Describe the bug
When editing the Blacklist (edit: same for the Wishlist too), the `Adding userdata (comprehensive sync)` checkbox is broken since a website update about 2 months ago. This of course breaks the userscript functionality to sync your Steam Ignored games to your Barter blacklist.

## Steps to reproduce the bug
1. Go to Blacklist, Edit, Add by ID
2. Fill up something, a single `app/????` is enough
3. Check `Adding userdata (comprehensive sync)`
4. Submit the form
5. Watch as PHP returns a completely empty response, and your data never got processed

## Expected behavior
Supplied apps/subs should be added to blacklist and the new page presented marking the differences from the previous state, as it worked before the feature broke.

### Screenshots
It's a completely empty (0 bytes) page, no errors, nothing to screenshot

### Additional context, device information (OS & Browser) if applicable 
Firefox 128

**Comment by bartervg** [comment]
Confirmed working https://discord.com/channels/329829406153375755/438406560222281738/1314427259465109595 

The bug was due to `count()` on an uncountable variable that resulted in a fatal error. Previously, it was a warning and the rest of the page would proceed as normal, thus hiding the problem. The upgrade to PHP 8 turned this into a fatal error and preventing the sync from working.
