### ISSUE TITLE
Marketplace

### ISSUE THREAD

**Issue by Revadike** [bartervg/barter.vg#35]
- Option to opt into selling (for each tradable)
 - Preference what payments to accept (tf2 keys, gems, paypal?, btc?)
 - Conversion rate between payment items determined by barter
 - Add input field for each tradable to set price of selling
 - Add a marketplace page where all the sales are listed and searchable

**Comment by bartervg** [comment]
In order to avoid creating Yet Another Vestigial Feature, someone should volunteer to lead this project. In the spirit of federation, it could be a separate site that is integrated via APIs. At the start, this would be a slower path, but it could lead to a better and more sustainable project.

**Comment by Luckz** [comment]
The idea of integrating a Barter-based G2A might not only encounter moral qualms, but also change the nature of the site.
Making it a core feature would for sure.

Examples, to illustrate the point:
- Letting people tag their tradable as Curator Connect helps transparency. Otherwise they'll trade the game copies all the same, just without proper tags, as happened before and still happens to a lesser degree.
- Letting people tag the individual expiration date of each of these promotes / encourages the use of Barter as a review copy trading (or even resale) platform.
  
So for this situation:

- Letting people include an item "unspecified real-money currency or equivalent" helps transparency. Otherwise, they'll use things like "[Nothing (free!)](https://barter.vg/i/34511/)" or TF2 keys / gems to represent real money. I assume this is the current practice.
- Letting people browse (and sort by price, etc) a central list of real money offers promotes game *resale*, and the use of Barter for this purpose.

If Barter becomes something closer to a grey market, communities who shun these have to be alerted not to link to or mention Barter anymore.

------

> Conversion rate between payment items determined by barter

See https://github.com/bartervg/barter.vg/issues/163#issuecomment-681973076 for complications.

**Comment by bartervg** [comment]
Out of Barter Scope. Divert related issues to dedicated project https://github.com/bartervg/notamarketplace
